name: Document Generation
run-name: ${{ github.actor }} is generating main documentation
on: [push]
jobs:
  Generate-Documentation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Generate the docs
        run: |
          cat 'Modules/01 - NIEM Training.md' > 'NIEM 101.md'
          cat 'Modules/02 - Introduction to NIEM.md' >> 'NIEM 101.md'
          cat 'Modules/03 - Message Spec (IEPD) Overview.md' >> 'NIEM 101.md'
          echo '___' >> 'NIEM 101.md'
          echo 'Generated on: ' >> 'NIEM 101.md'
          date >> 'NIEM 101.md'
          cat 'Modules/01 - NIEM Training.md' > 'Main NIEM XML Training Document.md'
          cat 'Modules/02 - Introduction to NIEM.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/03 - Message Spec (IEPD) Overview.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/04 - Scenario Planning.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/05 - Analyze Requirements.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/06 - XML Schema in a Nutshell.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/07 - Map and Model.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/08 - Mapping and NIEM Technical Details (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/09 - Native Properties.md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/10 - Substitution Groups (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/11 - Namespaces (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/12 - Inherited Properties (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/13 - Referencing (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/14 - Associations (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/15 - Roles (XML).md' >> 'Main NIEM XML Training Document.md'
          cat 'Modules/16 - Code Tables (XML).md' >> 'Main NIEM XML Training Document.md'
          echo '___' >> 'Main NIEM XML Training Document.md'
          echo 'Generated on: ' >> 'Main NIEM XML Training Document.md'
          date >> 'Main NIEM XML Training Document.md'
          cat 'Modules/01 - NIEM Training.md' > 'Main NIEM JSON Training Document.md'
          cat 'Modules/02 - Introduction to NIEM.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/03 - Message Spec (IEPD) Overview.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/04 - Scenario Planning.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/05 - Analyze Requirements.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/06 - JSON Schema in a Nutshell.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/07 - Map and Model.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/08 - Mapping and NIEM Technical Details (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/09 - Native Properties.md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/10 - Substitution Groups (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/11 - Namespaces (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/12 - Inherited Properties (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/13 - Referencing (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/14 - Associations (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/15 - Roles (JSON).md' >> 'Main NIEM JSON Training Document.md'
          cat 'Modules/16 - Code Tables (JSON).md' >> 'Main NIEM JSON Training Document.md'
          echo '___' >> 'Main NIEM JSON Training Document.md'
          echo 'Generated on: ' >> 'Main NIEM JSON Training Document.md'
          date >> 'Main NIEM JSON Training Document.md'
          git config --local user.email "Thomas.Carlson@gtri.gatech.edu"
          git config --local user.name "TomCarlson-NTAC"
          git add './NIEM 101.md'
          git add './Main NIEM XML Training Document.md'
          git add './Main NIEM JSON Training Document.md'
          git commit -m "Add changes"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - run: echo "🍏 This job's status is ${{ job.status }}."
