name: Document Generation
run-name: ${{ github.actor }} is generating main documentation
on: [push]
jobs:
  Generate-Documentation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          cat 'Modules/01 - NIEM Training.md' > 'Main NIEM Training Document.md'
          cat 'Modules/02 - Introduction to NIEM.md' >> 'Main NIEM Training Document.md'
          cat 'Modules/03 - Message Spec (IEPD) Overview.md' >> 'Main NIEM Training Document.md'
          cat 'Modules/04 - Scenario Planning.md' >> 'Main NIEM Training Document.md'
          echo '___' >> 'Main NIEM Training Document.md'
          echo 'Generated on: ' >> 'Main NIEM Training Document.md'
          date >> 'Main NIEM Training Document.md'
          ls ${{ github.workspace }}
          git config --local user.email "Thomas.Carlson@gtri.gatech.edu"
          git config --local user.name "TomCarlson-NTAC"
          git add './Main NIEM Training Document.md'
          git commit -m "Add changes"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - run: echo "🍏 This job's status is ${{ job.status }}."
